title: Leon Wong # your name (or website title) here
logo: "/images/iconpng.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <center>A youth passionate in video games. </center>
  <br>
  <center>Looking for opportunities in the game industry to further the skills and realize aspiration. </center>
  <br>
  <a href="https://www.artstation.com/carlos52">My Artstation Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
